apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xtxidgrud-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xtxidgrud-java-springboot-gitops